.\" Authors: Michael Hall
.TH axiomeatic 1 "August 2012" "0.1" "USER COMMANDS"
.SH NAME
axiomeatic \- User interface companion for AXIOME, based on PyGTK.
.SH SYNOPSIS
.B axiomeatic
.SH DESCRIPTION
Launches a PyGTK-based user interface which guides the user through the creation
of a \fB.ax\fR file for use with \fBAXIOME\fR (Automation, Extension, and Integration
of Microbial Ecology).
.SH SEE ALSO
.BR axiome (1).

